all:
  - Symfony\Bundle\FrameworkBundle\FrameworkBundle
  - Symfony\Bundle\TwigBundle\TwigBundle
  - Symfony\Bundle\SecurityBundle\SecurityBundle
  - Symfony\Bundle\MonologBundle\MonologBundle
  - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
  - Symfony\Bundle\DoctrineBundle\DoctrineBundle  
#  - Symfony\Bundle\DoctrineAbstractBundle\DoctrineAbstractBundle
#  - Symfony\Bundle\AsseticBundle\AsseticBundle
#  - Symfony\Bundle\DoctrineMigrationsBundle\DoctrineMigrationsBundle
#  - Symfony\Bundle\DoctrineMongoDBBundle\DoctrineMongoDBBundle
  - Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle

  - Sonata\jQueryBundle\SonatajQueryBundle
  - Sonata\BluePrintBundle\SonataBluePrintBundle
  - Sonata\AdminBundle\SonataAdminBundle
  - Knplabs\Bundle\MenuBundle\KnplabsMenuBundle
  - FOS\UserBundle\FOSUserBundle

  - rs\kaoz4Bundle\kaoz4Bundle
#  - rs\ProjectUtilitiesBundle\ProjectUtilitiesBundle
  
dev:
  - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
  
test:
  - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle

cli:
  - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
  